version: '3.8'
services:
  app:
    image: spintrip555/spintrip-backend:7.0
    ports:
      - "2000:2000"
    environment:
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASSWORD=1234
      - DB_PORT=5432
      - DB_NAME=mydatabase
    depends_on:
      - db
    # Only include volumes if you need to mount data into the container
    # volumes:
    #   - .:/usr/src/app
    #   - /usr/src/app/node_modules

  db:
    image: postgres:16
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=mydatabase
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
