version: '3.8'
services:
  app:
    image: spintrip555/spintrip_backend:22.0
    ports:
      - "2000:2000"
    environment:
      - DB_HOST=3.108.218.32
      - DB_USER=postgres
      - DB_PASSWORD=1234
      - DB_PORT=5000
      - DB_NAME=mydatabase
